apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: platform-config
