apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-grafana.yaml
  - helmrepository-prometheus.yaml
  - grafana-helmrelease.yaml
  - prometheus-helmrelease.yaml
