apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository-grafana.yaml
  - helmrepository-prometheus.yaml
  - kube-prometheus-helmrelease.yaml
  - loki-helmrelease.yaml
